### ISSUE TITLE
Channels menu jumps back and forth if the cursor is positioned between guilds and channel list

### ISSUE THREAD

**Issue by Xaero252** [madmaxgrey/Vertical-Spacious-Refresh#1]
It's pretty silly, but basically there's a small gap when you expand the channel list it goes past the gap and then the cursor is no longer over it, causing the panel to start to close and then open repeatedly. 

The fix is quite easy:
```css
.sidebarList_c48ade {
    margin-left: -10px;
    padding-left: 10px;
}
```

This causes the margin of the sidebar container to cover the gap. The margin is invisible render-wise but still interacts with the cursor preventing the hover state juggle.
