### ISSUE TITLE
Mobile status indicators missing from user list

### ISSUE THREAD

**Issue by Xaero252** [madmaxgrey/Vertical-Spacious-Refresh#2]
This was probably an intentional decision because keeping them with the radial status is really difficult. 

I came up with this solution:
```css
/* Mobile Status Indicator */
[class^=avatar__]:has([aria-label*="Online via mobile"])~[class^=content__]>[class^=nameAndDecorators__]:before {
  content: "";
  width: 10px;
  height: 15px;
  margin-right: 4px;
  mask: url(#svg-mask-status-online-mobile);
  stroke: var(--rs-phone-color, var(--rs-online-color));
  background: var(--rs-phone-color, var(--rs-online-color));
}
```

Looks like this:

![Image](https://github.com/user-attachments/assets/d792e0b6-a6bf-48f6-8c0f-58e7b6fab42f)
